### ISSUE TITLE
git clone

### ISSUE THREAD

**Issue by wwieder** [NCAR/CTSM-Tutorial-2022#1]
For the tutorial I suggest we get users used to the quick start way of interacting with github and cloning from the development branch of CTSM [see slide 20 from the 2019 tutorial](https://www.cgd.ucar.edu/events/2019/ctsm/files/practical1-lombardozzi.pdf)

@negin513 and @adrifoster I'd assume this makes sense to include in the pre-tutorial homework and webcast recording?
Does this make sense to you @danicalombardozzi ?

**Comment by wwieder** [comment]
@briandobbins will this work OK in the container?

**Comment by briandobbins** [comment]
Yes, this should work fine in both the container and the cloud.

And just to clarify a bit - you _can_ run containers in the cloud, but you don't have to.  Our cloud infrastructure is currently not in a container, it's just like logging into a remote system that's configured on launch.  So while we keep the software identical between our container/cloud platforms, one doesn't necessitate the other.

Finally, as another clarification, what we _often_ do (in both!) is provide a built-in version of CESM - since most people are just looking to do runs, this makes it easier.  They can select a version and it's there.  For _this_ tutorial, given that slide, we probably want it without one preinstalled, so everyone is sure to use the one from their directory, correct?  You're teaching people to 'git clone' it themselves.  So a built-in version isn't needed, just that the 'git clone' version works without needing to do system configuration too, correct?

Definitely easy, I just wanted to be sure.

**Comment by wwieder** [comment]
I don't think it's too much to ask users to run two extra lines of code: `git clone` and then `manage externals`.  This seems like the basics of what people will need to do when they really want to run CTSM outside the tutorial, so it's better to set up our tutorial examples accordingly.  What do others think?

**Comment by adrifoster** [comment]
Hey Will,

I agree that including some basic git instructions in the "setup" video is
a fine idea. Do we want to have them fork as well?  If we are doing the
code modifications tutorial this may be helpful to include as an initial
step and just explain what we are doing there.

**Comment by adrifoster** [comment]
> At this point I don't think we want to include the fork example, mainly because I don't want workshop participants to have to create their own github account.
> 
> I do think this could be provided in a more advanced developers tutorial (if we ever get to that point), similar to the recommendations we have for quick start for [users](https://github.com/ESCOMP/CTSM/wiki/CTSM-Quickstart-Guide-for-Users) vs. [developers](https://github.com/ESCOMP/CTSM/wiki/Quick-start-to-CTSM-development-with-git) on the ctsm/wiki .

Ah okay that makes sense.  We can always link to those resources for now if they want to go further.
